# Generated by Django 6.0.3 on 2026-03-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uddy_api', '0002_alter_subject_weekly_study_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
