# Generated by Django 6.0.3 on 2026-03-26 16:15

import django.db.models.deletion
from django.db import migrations, models

def create_categories(apps, schema_editor): # For some reason `schema_editor` is needed
    SubjectCategory = apps.get_model('uddy_api', 'SubjectCategory')

    categories = [
        'Accounting',
        'Biology',
        'Computes Science',
        'Engineering',
        'History',
        'Humanities',
        'Literature',
        'Marketing',
        'Math',
        'Psychology',
        'Science',
    ]

    for name in categories:
        SubjectCategory.objects.get_or_create(name=name)

class Migration(migrations.Migration):

    dependencies = [
        ('uddy_api', '0003_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='color',
            field=models.CharField(default='bg-amber-200', max_length=50),
        ),
        migrations.AddField(
            model_name='subject',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='uddy_api.subjectcategory'),
        ),
    ]
