# Generated by Django 6.0.3 on 2026-03-26 16:22

from django.db import migrations

def create_categories(apps, schema_editor):
    SubjectCategory = apps.get_model('uddy_api', 'SubjectCategory')

    categories = [
        'Accounting', 'Biology', 'Computer Science', 'Engineering',
        'History', 'Humanities', 'Literature', 'Marketing',
        'Math', 'Psychology', 'Science',
    ]

    for name in categories:
        SubjectCategory.objects.get_or_create(name=name)

class Migration(migrations.Migration):

    dependencies = [
        ('uddy_api', '0004_subjectcategory_subject_color_subject_category'),
    ]

    operations = [
        migrations.RunPython(create_categories),
    ]