# Generated by Django 6.0.3 on 2026-03-27 16:37

from django.db import migrations, models

def add_colors(apps, schema_editor):
    SubjectCategory = apps.get_model('uddy_api', 'SubjectCategory')

    # Standard tailwind color format:
        # bg-color-xxx
    # All colors in the 200s look good

    colors = {
        'Accounting': 'bg-red-200',
        'Biology': 'bg-green-200',
        'Computer Science': 'bg-blue-200',
        'Engineering': 'bg-orange-200',
        'History': 'bg-yellow-200',
        'Humanities': 'bg-purple-200',
        'Literature': 'bg-pink-200',
        'Marketing': 'bg-cyan-200',
        'Math': 'bg-indigo-200',
        'Psychology': 'bg-lime-200',
        'Science': 'bg-slate-200',
    }

    for name, color in colors.items():
        SubjectCategory.objects.filter(name=name).update(color=color)

class Migration(migrations.Migration):

    dependencies = [
        ('uddy_api', '0005_auto_20260326_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='color',
        ),
        migrations.AddField(
            model_name='subjectcategory',
            name='color',
            field=models.CharField(default='bg-amber-200', max_length=50),
        ),
        
        # Change the colors
        migrations.RunPython(add_colors)
    ]
