# Generated by Django 6.0.3 on 2026-03-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uddy_api', '0006_remove_subject_color_subjectcategory_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectcategory',
            name='color',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
