# Generated by Django 6.0.3 on 2026-03-29 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uddy_api', '0008_auto_20260327_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='workflow',
        ),
        migrations.AddField(
            model_name='subject',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Workflow',
        ),
    ]
