# Generated by Django 6.0.3 on 2026-04-04 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uddy_api', '0009_remove_subject_workflow_subject_user_delete_workflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('total_minutes', models.IntegerField(default=0)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uddy_api.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'subject', 'week_start')},
            },
        ),
        migrations.DeleteModel(
            name='SubjectDays',
        ),
    ]
