# Generated by Django 6.0.3 on 2026-07-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uddy_api', '0011_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='recipient_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='challenge',
            name='sender_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('recipient_done', 'Recipient Done'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
