# Generated by Django 6.0.3 on 2026-08-02 15:41

import uddy_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uddy_api', '0013_emailverificationtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverificationtoken',
            name='token',
        ),
        migrations.AddField(
            model_name='emailverificationtoken',
            name='code',
            field=models.CharField(default=uddy_api.models.generate_verification_code, max_length=6),
        ),
    ]
